services:
  rstudio:
    container_name: rstudio
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PASSWORD="rstudio"
      - ROOT=true
      - DISABLE_AUTH=true
    ports:
      - 8787:8787
    volumes:
      - ./:/home/rstudio/Dev
